set_property SRC_FILE_INFO {cfile:C:/Users/user/Desktop/vivado_projects/Anas_tutorial/first_project/first_project.srcs/constrs_1/imports/source_files/Basys-3-Master.xdc rfile:../../../first_project.srcs/constrs_1/imports/source_files/Basys-3-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R2    IOSTANDARD LVCMOS33 } [get_ports {I}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L1    IOSTANDARD LVCMOS33 } [get_ports {O}]
